/**
 * Admin concurrency + credential-security integration tests (wave-15, P-4 load-bearing).
 *
 * GUARD: suite is skipped when TEST_DATABASE_URL is unset or DB unreachable.
 *
 * ── RACE-SAFE last-admin guard (CONCURRENCY TEST — P-4 load-bearing) ────────
 * Test CONC-1: Two concurrent transactions each attempt to deactivate a DIFFERENT
 * one of the last two admins. The advisory-lock guard must ensure EXACTLY ONE
 * succeeds — the second is rejected with 409. At least one admin always remains.
 *
 * This test PROVES that pg_advisory_xact_lock(ADMIN_GUARD_LOCK_KEY) closes the
 * write-skew window that a plain `count(*) FOR UPDATE` cannot close.
 *
 * The test calls the REAL UserManagementService.deactivateAsActor (not inline SQL).
 * Fault-killing property: if the production guard regressed to count(*)-FOR-UPDATE,
 * two concurrent deactivateAsActor calls on DIFFERENT last-two admins would BOTH
 * read count=2 (one for each, excluding themselves → 1 remaining each), BOTH
 * proceed, and both succeed → 0 admins remain. The "exactly one fulfilled + ≥1
 * remains" assertion would then FAIL, catching the regression.
 *
 * ── CREDENTIAL NEVER LEAKS (SECURITY TEST — P-4 load-bearing) ───────────────
 * Test SEC-1: The credential is absent from the audit row written during
 * createConnection. (Asserts on the real audit_log_entries row.)
 *
 * Test SEC-2: The credential is absent from a FORCED-error path.
 * Trigger a DB error (constraint violation on displayName unique index) WHILE
 * a credential is present in the input. Assert the thrown error does NOT contain
 * the plaintext credential.
 *
 * Test SEC-3: round-trip encrypt → decrypt (also in unit tests; repeated here
 * to confirm the CI CREDENTIALS_ENC_KEY env var is set and works end-to-end).
 *
 * Test SEC-4: GET /admin/integrations (via DataSourceAdminService.listConnections)
 * never returns the plaintext credential — only hasCredential boolean.
 *
 * ── UUID NAMESPACE ───────────────────────────────────────────────────────────
 * Wave-15 prefix '00000015-*' — disjoint from all prior suites:
 *   outreach-gate:    10000000-60000000
 *   pipeline-gate:    00000012-*
 *   recordkeeping:    00000014-*
 *
 * ── TEARDOWN POLICY (WORM-SAFE) ──────────────────────────────────────────────
 * All tests call real service methods that commit audit_log_entries rows with
 * actor_user_id pointing at the seeded users. Deleting those users would trigger
 * the ON DELETE SET NULL FK on audit_log_entries.actor_user_id, which fires an
 * UPDATE on an immutable table → audit_log_block_mutation() raises P0001.
 *
 * LESSON from wave-12/13/14: DO NOT hard-delete users (or any row FK-referenced
 * by an immutable audit_log_entries row). Instead:
 *   • All user fixtures are RETAINED across runs.
 *   • Per-test state resets (deactivated_at, role) are done via UPDATE.
 *   • data_source_connections (not FK-referenced by audit_log_entries) are
 *     hard-deleted in finally blocks as before.
 *   • Dynamic (Date.now) email fixtures generated by SEC tests accumulate across
 *     runs but are isolated to the wave-15 namespace and do not affect other suites.
 */

import path from 'node:path';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { apiMigrationsFolder, ensureMigrated } from './_helpers/ensure-migrated';

// ── Guard ───────────────────────────────────────────────────────────────────
const TEST_DB_URL = process.env.TEST_DATABASE_URL;
const shouldSkip = !TEST_DB_URL || TEST_DB_URL.trim() === '';

if (shouldSkip) {
  console.info(
    '[admin-concurrency] TEST_DATABASE_URL is not set — suite SKIPPED. ' +
      'Set TEST_DATABASE_URL to a reachable Postgres instance with migrations applied.'
  );
}

async function isDbReachable(url: string): Promise<boolean> {
  const pool = new Pool({ connectionString: url, connectionTimeoutMillis: 3000 });
  try {
    await pool.query('SELECT 1');
    return true;
  } catch {
    return false;
  } finally {
    await pool.end();
  }
}

// biome-ignore lint/suspicious/noExplicitAny: lazy DB handle populated in beforeAll
let db: any;
let dbReachable = false;

describe.skipIf(shouldSkip)(
  'Admin integration — race-safe last-admin guard + credential-never-leaks',
  () => {
    beforeAll(async () => {
      if (!TEST_DB_URL) return;
      dbReachable = await isDbReachable(TEST_DB_URL);
      if (!dbReachable) {
        console.info('[admin-concurrency] Postgres unreachable — tests will be skipped.');
        return;
      }

      process.env.DATABASE_URL = TEST_DB_URL;
      process.env.AUDIT_LOG_HMAC_KEY =
        process.env.AUDIT_LOG_HMAC_KEY ?? 'test-audit-hmac-key-dummy-do-not-use-in-prod';
      process.env.AUDIT_LOG_HMAC_KEY_VERSION = process.env.AUDIT_LOG_HMAC_KEY_VERSION ?? '1';
      process.env.CREDENTIALS_ENC_KEY =
        process.env.CREDENTIALS_ENC_KEY ?? 'dGVzdC1jcmVkZW50aWFscy1rZXktMzItYnl0ZXMhISE=';

      const { drizzle } = await import('drizzle-orm/node-postgres');
      const { Pool: PgPool } = await import('pg');
      const pool = new PgPool({ connectionString: TEST_DB_URL });
      const schema = await import('../src/db/schema');
      db = drizzle(pool, { schema });

      await ensureMigrated(
        db,
        apiMigrationsFolder(path.resolve(import.meta.url.replace('file://', ''), '..'))
      );
    });

    afterAll(async () => {
      // DB handle cleanup — let vitest/node handle pool termination
    });

    // ── Helpers ──────────────────────────────────────────────────────────────

    /** Resolve a role id by name. */
    async function getRoleId(name: string): Promise<string> {
      const { sql } = await import('drizzle-orm');
      const rows = await db.execute<{ id: string }>(sql`
        SELECT id FROM roles WHERE name = ${name} LIMIT 1
      `);
      const id = (rows.rows ?? rows)[0]?.id;
      if (!id) throw new Error(`Role '${name}' not found in roles table`);
      return id;
    }

    /**
     * Insert a minimal test user with a known role. Returns the users.id UUID.
     *
     * WORM-SAFE: uses ON CONFLICT (email) DO NOTHING so re-runs that hit the same
     * email (e.g. fixed wave-15 fixture emails) are idempotent. Dynamic Date.now()
     * emails used by CONC tests generate new rows each run — those are retained
     * (never deleted) because they accumulate audit_log_entries references.
     *
     * NOTE: returning id after ON CONFLICT DO NOTHING requires a two-step approach
     * (INSERT then SELECT) because ON CONFLICT DO NOTHING yields no RETURNING row
     * on the conflict branch. We INSERT first; if it returns a row we use it,
     * otherwise we SELECT the existing row.
     */
    async function createTestUser(email: string, roleName: string): Promise<string> {
      const { sql } = await import('drizzle-orm');
      const roleId = await getRoleId(roleName);
      // Try insert; returns the new row or nothing if email already exists.
      const insertRows = await db.execute<{ id: string }>(sql`
        INSERT INTO users (supertokens_user_id, email, role_id)
        VALUES (gen_random_uuid()::text, ${email}, ${roleId}::uuid)
        ON CONFLICT (email) DO NOTHING
        RETURNING id
      `);
      const inserted = (insertRows.rows ?? insertRows)[0]?.id;
      if (inserted) return inserted;
      // Email already existed — fetch the existing user id.
      const selectRows = await db.execute<{ id: string }>(sql`
        SELECT id FROM users WHERE email = ${email} LIMIT 1
      `);
      const existing = (selectRows.rows ?? selectRows)[0]?.id;
      if (!existing) throw new Error(`User with email ${email} not found after conflict`);
      return existing;
    }

    /**
     * Reset a test user's deactivated_at to NULL and optionally restore its role.
     * Used INSTEAD of deleteTestUser — avoids triggering the WORM audit FK.
     */
    async function resetTestUser(userId: string, roleName?: string): Promise<void> {
      const { sql } = await import('drizzle-orm');
      if (roleName) {
        const roleId = await getRoleId(roleName);
        await db.execute(sql`
          UPDATE users SET deactivated_at = NULL, role_id = ${roleId}::uuid
          WHERE id = ${userId}::uuid
        `);
      } else {
        await db.execute(sql`
          UPDATE users SET deactivated_at = NULL WHERE id = ${userId}::uuid
        `);
      }
    }

    /** Hard-delete a test data_source_connection by id. */
    async function deleteTestConnection(connId: string): Promise<void> {
      const { sql } = await import('drizzle-orm');
      await db.execute(sql`DELETE FROM data_source_connections WHERE id = ${connId}::uuid`);
    }

    /**
     * Build a REAL UserManagementService wired against the live test DB.
     * Mirrors the pattern used by outreach-gate.e2e-spec.ts for building
     * real services: instantiate AuditKeyring → AuditRepository → AuditService
     * → UserManagementService, passing `db` directly (bypassing NestJS DI).
     */
    async function buildUserManagementService() {
      const { AuditKeyring } = await import('../src/modules/audit/audit.keyring');
      const { AuditRepository } = await import('../src/modules/audit/audit.repository');
      const { AuditService } = await import('../src/modules/audit/audit.service');
      const { UserManagementService } = await import(
        '../src/modules/admin/user-management.service'
      );

      const keyring = new AuditKeyring(process.env);
      const auditRepo = new AuditRepository(db);
      const auditService = new AuditService(keyring, auditRepo);
      return new UserManagementService(db, auditService);
    }

    // ── CONC-1: Race-safe last-admin guard ──────────────────────────────────

    it('CONC-1: two concurrent deactivate attempts on different last-two-admins — exactly one succeeds, ≥1 admin always remains', {
      timeout: 15000,
    }, async () => {
      if (!dbReachable) return;

      const { sql } = await import('drizzle-orm');
      const { ConflictException } = await import('@nestjs/common');

      // Seed exactly two fresh admin users.  We cannot control pre-existing
      // admins, but the guard counts ALL active admins — so we first count
      // how many admins already exist and only proceed if the DB already has
      // zero active non-test admins, OR we accept that pre-existing admins
      // would prevent the guard from firing (guard sees >2 remaining → both
      // succeed → test assertion fails).  To guarantee the guard fires we
      // need to ensure EXACTLY 2 active admins are present when the concurrent
      // calls hit.  We deactivate all pre-existing admins within the test and
      // restore them after (a controlled, isolated approach for the write-skew
      // proof).
      //
      // Simpler approach: accept DB may have pre-existing admins.  Instead of
      // deactivating them (risky for shared CI state), we seed 2 new admins and
      // rely on the guard's cross-connection advisory lock to serialize the
      // concurrent calls correctly even in the presence of other admins.  If
      // there are pre-existing admins the guard won't fire (both calls succeed
      // because count-excluding-self > 0 for both).  That would also FAIL our
      // "exactly one rejected" assertion — so the test is still honest about
      // the environment state.
      //
      // Correct approach for a deterministic test: deactivate ALL pre-existing
      // admins (other than our two seeds) WITHIN this test, prove write-skew,
      // then restore.  But that modifies shared state.  The safest approach that
      // does NOT corrupt shared state is to use ONLY our two newly-created admins
      // and hard-deactivate any other admins WITHIN the test scope, restoring
      // them after.
      //
      // FINAL APPROACH: count and snapshot pre-existing active admins.
      // Temporarily deactivate them, run the concurrent proof, restore them.
      // This is safe because we restore in a finally block.

      // 1. Create our two test admins.
      const ts = Date.now();
      const admin1 = await createTestUser(`conc1-a-${ts}@test.invalid`, 'admin');
      const admin2 = await createTestUser(`conc1-b-${ts}@test.invalid`, 'admin');

      // 2. Snapshot and temporarily deactivate any OTHER active admins so the
      //    guard sees exactly 2 active admins during our concurrent calls.
      //    DEFECT-A FIX: qualify the ambiguous column as u.id (users and roles
      //    both have an id column — unqualified causes Postgres 42702).
      const preExisting = await db.execute<{ id: string }>(sql`
          SELECT u.id FROM users u
          INNER JOIN roles r ON u.role_id = r.id
          WHERE r.name = 'admin'
            AND u.deactivated_at IS NULL
            AND u.id NOT IN (${admin1}::uuid, ${admin2}::uuid)
        `);
      const preExistingIds: string[] = (preExisting.rows ?? preExisting).map(
        (r: { id: string }) => r.id
      );

      // Temporarily deactivate pre-existing admins.
      for (const id of preExistingIds) {
        await db.execute(sql`
            UPDATE users SET deactivated_at = now() WHERE id = ${id}::uuid
          `);
      }

      try {
        // 3. Build a REAL UserManagementService — calls the ACTUAL advisory-lock guard.
        const svc = await buildUserManagementService();

        // 4. Run TWO CONCURRENT deactivateAsActor calls: each targeting a DIFFERENT
        //    one of the only two active admins.  The advisory-lock serializes them;
        //    the second sees count-excluding-self = 0 → ConflictException (409).
        //
        //    FAULT-KILLING PROPERTY: if the guard regressed to count(*) FOR UPDATE
        //    (write-skew), both transactions could read count=1 (excluding their own
        //    user) at the same time, both pass the guard, both commit → 0 active
        //    admins.  The "exactly one rejected" assertion below would then FAIL,
        //    exposing the regression.
        const results = await Promise.allSettled([
          svc.deactivateAsActor(admin1, admin1, 'admin'),
          svc.deactivateAsActor(admin2, admin2, 'admin'),
        ]);

        const fulfilled = results.filter((r) => r.status === 'fulfilled');
        const rejected = results.filter((r) => r.status === 'rejected');

        // EXACTLY ONE must succeed.
        expect(fulfilled).toHaveLength(1);
        // EXACTLY ONE must be rejected.
        expect(rejected).toHaveLength(1);

        // The rejection MUST be a ConflictException (409 from the last-admin guard).
        // Not a random DB error — it must be the guard itself firing.
        const rejectedReason = (rejected[0] as PromiseRejectedResult).reason;
        expect(rejectedReason).toBeInstanceOf(ConflictException);
        expect((rejectedReason as ConflictException).message).toMatch(
          /Cannot (deactivate|demote) the last active admin/i
        );

        // DB state: at least one of our two test admins remains active.
        const activeCount = await db.execute<{ count: string }>(sql`
            SELECT COUNT(*)::text AS count
            FROM users u
            INNER JOIN roles r ON u.role_id = r.id
            WHERE r.name = 'admin'
              AND u.deactivated_at IS NULL
              AND u.id IN (${admin1}::uuid, ${admin2}::uuid)
          `);
        const remaining = Number((activeCount.rows ?? activeCount)[0]?.count ?? 0);
        expect(remaining).toBeGreaterThanOrEqual(1);
      } finally {
        // Restore any pre-existing admins we temporarily deactivated.
        for (const id of preExistingIds) {
          await db.execute(sql`
              UPDATE users SET deactivated_at = NULL WHERE id = ${id}::uuid
            `);
        }
        // WORM-SAFE: reset our two test admins' state via UPDATE (no DELETE).
        // deactivateAsActor committed audit rows referencing these user IDs —
        // hard-deleting them would trigger ON DELETE SET NULL on
        // audit_log_entries.actor_user_id which the immutability trigger blocks.
        await resetTestUser(admin1, 'admin');
        await resetTestUser(admin2, 'admin');
      }
    });

    // ── CONC-2: Happy path — deactivating a non-last admin succeeds ──────────

    it('CONC-2: deactivating a non-last admin succeeds when >2 admins are active', {
      timeout: 10000,
    }, async () => {
      if (!dbReachable) return;

      // Seed 3 admins so deactivating one of them cannot trigger the guard.
      const ts = Date.now();
      const admin1 = await createTestUser(`conc2-a-${ts}@test.invalid`, 'admin');
      const admin2 = await createTestUser(`conc2-b-${ts}@test.invalid`, 'admin');
      const admin3 = await createTestUser(`conc2-c-${ts}@test.invalid`, 'admin');

      try {
        const svc = await buildUserManagementService();
        // Deactivating admin1 when admin2+admin3 also exist → guard passes.
        const result = await svc.deactivateAsActor(admin1, admin1, 'admin');
        expect(result.id).toBe(admin1);
        expect(result.deactivatedAt).toBeTruthy();
      } finally {
        // WORM-SAFE: reset state via UPDATE (deactivateAsActor committed audit rows).
        await resetTestUser(admin1, 'admin');
        await resetTestUser(admin2, 'admin');
        await resetTestUser(admin3, 'admin');
      }
    });

    // ── CONC-3: demote-last-admin → 409 ─────────────────────────────────────

    it('CONC-3: demoting the last active admin → 409 ConflictException', {
      timeout: 10000,
    }, async () => {
      if (!dbReachable) return;

      const { sql } = await import('drizzle-orm');
      const { ConflictException } = await import('@nestjs/common');

      const ts = Date.now();
      const lastAdmin = await createTestUser(`conc3-a-${ts}@test.invalid`, 'admin');

      // Temporarily deactivate all other admins.
      // DEFECT-A FIX: qualify the ambiguous column as u.id.
      const preExisting = await db.execute<{ id: string }>(sql`
          SELECT u.id FROM users u
          INNER JOIN roles r ON u.role_id = r.id
          WHERE r.name = 'admin'
            AND u.deactivated_at IS NULL
            AND u.id != ${lastAdmin}::uuid
        `);
      const preExistingIds: string[] = (preExisting.rows ?? preExisting).map(
        (r: { id: string }) => r.id
      );
      for (const id of preExistingIds) {
        await db.execute(sql`UPDATE users SET deactivated_at = now() WHERE id = ${id}::uuid`);
      }

      try {
        const svc = await buildUserManagementService();
        // Attempt to demote the only active admin to 'advisor'.
        await expect(
          svc.assignRoleAsActor(lastAdmin, 'advisor', lastAdmin, 'admin')
        ).rejects.toBeInstanceOf(ConflictException);
      } finally {
        for (const id of preExistingIds) {
          await db.execute(sql`UPDATE users SET deactivated_at = NULL WHERE id = ${id}::uuid`);
        }
        // WORM-SAFE: the 409 path throws before committing any audit row for
        // lastAdmin, but the guard itself may have written nothing — either way
        // resetTestUser is safe and keeps state clean for re-runs.
        await resetTestUser(lastAdmin, 'admin');
      }
    });

    // ── CONC-4: self-deactivate-last-admin → 409 ────────────────────────────

    it('CONC-4: self-deactivating the last active admin → 409 ConflictException', {
      timeout: 10000,
    }, async () => {
      if (!dbReachable) return;

      const { sql } = await import('drizzle-orm');
      const { ConflictException } = await import('@nestjs/common');

      const ts = Date.now();
      const lastAdmin = await createTestUser(`conc4-a-${ts}@test.invalid`, 'admin');

      // DEFECT-A FIX: qualify the ambiguous column as u.id.
      const preExisting = await db.execute<{ id: string }>(sql`
          SELECT u.id FROM users u
          INNER JOIN roles r ON u.role_id = r.id
          WHERE r.name = 'admin'
            AND u.deactivated_at IS NULL
            AND u.id != ${lastAdmin}::uuid
        `);
      const preExistingIds: string[] = (preExisting.rows ?? preExisting).map(
        (r: { id: string }) => r.id
      );
      for (const id of preExistingIds) {
        await db.execute(sql`UPDATE users SET deactivated_at = now() WHERE id = ${id}::uuid`);
      }

      try {
        const svc = await buildUserManagementService();
        // Self-deactivation of the only active admin must reject with 409.
        await expect(svc.deactivateAsActor(lastAdmin, lastAdmin, 'admin')).rejects.toBeInstanceOf(
          ConflictException
        );
      } finally {
        for (const id of preExistingIds) {
          await db.execute(sql`UPDATE users SET deactivated_at = NULL WHERE id = ${id}::uuid`);
        }
        // WORM-SAFE: 409 path throws before committing audit rows; reset is safe.
        await resetTestUser(lastAdmin, 'admin');
      }
    });

    // ── INVITE-CONC-1: Concurrent invite dedup — exactly one invite row ────────
    //
    // FAULT-KILLING property (VERIFY rule 3):
    // If pg_advisory_xact_lock(hashtext(email)::bigint) is removed from
    // inviteAsActor, two concurrent calls for the same fresh email could
    // both pass the SELECT-live-check (no live invite seen) and both INSERT.
    // Two invite rows would then exist for the same email. The "exactly one
    // invite row" assertion below would FAIL, catching the regression.
    //
    // We DO NOT re-implement the advisory lock inline — we call the REAL
    // UserManagementService.inviteAsActor (VERIFY rule 3 compliance).

    it('INVITE-CONC-1: two concurrent inviteAsActor for the same fresh email — exactly one invite row, the other gets 409', {
      timeout: 15000,
    }, async () => {
      if (!dbReachable) return;

      const { sql } = await import('drizzle-orm');
      const { ConflictException } = await import('@nestjs/common');

      const ts = Date.now();
      const email = `invite-conc-${ts}@test.invalid`;

      // Actor must exist in the DB so the invited_by FK is valid.
      const actorId = await createTestUser(`invite-conc-actor-${ts}@test.invalid`, 'admin');

      const svc = await buildUserManagementService();

      // Two concurrent inviteAsActor calls for the SAME fresh email.
      const results = await Promise.allSettled([
        svc.inviteAsActor({ email, role: 'advisor' }, actorId, 'admin'),
        svc.inviteAsActor({ email, role: 'advisor' }, actorId, 'admin'),
      ]);

      const fulfilled = results.filter((r) => r.status === 'fulfilled');
      const rejected = results.filter((r) => r.status === 'rejected');

      // EXACTLY ONE must succeed (one invite row inserted).
      expect(fulfilled).toHaveLength(1);
      // EXACTLY ONE must be rejected with 409 ConflictException.
      expect(rejected).toHaveLength(1);

      const rejectedReason = (rejected[0] as PromiseRejectedResult).reason;
      expect(rejectedReason).toBeInstanceOf(ConflictException);

      // Verify the DB has exactly one invite row for this email.
      const inviteRows = await db.execute<{ id: string }>(sql`
        SELECT id FROM invites WHERE email = ${email} ORDER BY created_at
      `);
      const rows = (inviteRows.rows ?? inviteRows) as { id: string }[];
      expect(rows).toHaveLength(1);

      // Teardown: hard-delete the invite (not FK-referenced by audit_log_entries).
      const inviteId = rows[0]!.id;
      await db.execute(sql`DELETE FROM invites WHERE id = ${inviteId}::uuid`);
      // WORM-SAFE: retain actorId (it was used as invitedBy FK for the audit row).
    });

    // ── REACTIVATE-1: Real-service reactivate integration ───────────────────
    //
    // Proves: deactivated_at → NULL, audit row appended, chain still verifies,
    // already-active → 400, role_id preserved.

    it('REACTIVATE-1: reactivateAsActor on a deactivated user sets deactivated_at=null + appends audit row', {
      timeout: 15000,
    }, async () => {
      if (!dbReachable) return;

      const { sql } = await import('drizzle-orm');

      const ts = Date.now();
      // Seed a deactivated user.
      const userId = await createTestUser(`reactivate-1-${ts}@test.invalid`, 'advisor');
      // Deactivate them directly (bypassing the service guard — they are not admin).
      await db.execute(sql`UPDATE users SET deactivated_at = now() WHERE id = ${userId}::uuid`);

      const actorId = await createTestUser(`reactivate-actor-${ts}@test.invalid`, 'admin');

      const svc = await buildUserManagementService();

      const result = await svc.reactivateAsActor(userId, actorId, 'admin');

      // deactivatedAt must now be null.
      expect(result.id).toBe(userId);
      expect(result.deactivatedAt).toBeNull();

      // Confirm the DB row has deactivated_at = NULL.
      const userRows = await db.execute<{ deactivated_at: string | null }>(sql`
        SELECT deactivated_at FROM users WHERE id = ${userId}::uuid
      `);
      const dbRow = (userRows.rows ?? userRows)[0] as { deactivated_at: string | null } | undefined;
      expect(dbRow).toBeDefined();
      expect(dbRow!.deactivated_at).toBeNull();

      // An audit row with action='user-reactivate' must exist.
      const auditRows = await db.execute<{ action: string }>(sql`
        SELECT action FROM audit_log_entries
        WHERE resource_type = 'user'
          AND resource_id = ${userId}
          AND action = 'user-reactivate'
        ORDER BY sequence_number DESC
        LIMIT 1
      `);
      const auditRow = (auditRows.rows ?? auditRows)[0] as { action: string } | undefined;
      expect(auditRow).toBeDefined();
      expect(auditRow!.action).toBe('user-reactivate');

      // role_id must be unchanged (still advisor).
      const roleRows = await db.execute<{ name: string }>(sql`
        SELECT r.name FROM users u
        INNER JOIN roles r ON u.role_id = r.id
        WHERE u.id = ${userId}::uuid
      `);
      const roleName = ((roleRows.rows ?? roleRows)[0] as { name: string } | undefined)?.name;
      expect(roleName).toBe('advisor');

      // WORM-SAFE teardown: retain both users (audit rows reference actorId as actor_user_id).
      // No DELETE — reset state via UPDATE.
      await resetTestUser(userId, 'advisor');
    });

    it('REACTIVATE-2: reactivateAsActor on an already-active user → 400 BadRequestException', {
      timeout: 10000,
    }, async () => {
      if (!dbReachable) return;

      const { BadRequestException } = await import('@nestjs/common');
      const ts = Date.now();
      const userId = await createTestUser(`reactivate-2-${ts}@test.invalid`, 'advisor');
      const actorId = await createTestUser(`reactivate-2-actor-${ts}@test.invalid`, 'admin');

      const svc = await buildUserManagementService();

      // User is active (deactivated_at IS NULL) — must throw 400.
      await expect(svc.reactivateAsActor(userId, actorId, 'admin')).rejects.toBeInstanceOf(
        BadRequestException
      );

      // WORM-SAFE: no audit rows were written (400 path); safe to reset.
      await resetTestUser(userId, 'advisor');
      await resetTestUser(actorId, 'admin');
    });

    // ── SEC-1: Credential absent from audit row ──────────────────────────────

    it('SEC-1: credential is absent from the audit_log_entries row written during createConnection', {
      timeout: 10000,
    }, async () => {
      if (!dbReachable) return;

      const { sql } = await import('drizzle-orm');

      // Get/create an actor user.
      const actorId = await createTestUser(`admin-sec1-${Date.now()}@test.com`, 'admin');

      const { DataSourceAdminService } = await import(
        '../src/modules/admin/data-source-admin.service'
      );
      const { AuditService } = await import('../src/modules/audit/audit.service');
      const { AuditRepository } = await import('../src/modules/audit/audit.repository');
      const { AuditKeyring } = await import('../src/modules/audit/audit.keyring');

      const keyring = new AuditKeyring(process.env);
      const auditRepo = new AuditRepository(db);
      const auditService = new AuditService(keyring, auditRepo);
      const service = new DataSourceAdminService(db, auditService);

      const uniqueName = `SEC1-test-${Date.now()}`;
      const plainCredential = `super-secret-${Date.now()}`;
      let connId: string | undefined;

      try {
        const conn = await service.createConnection(
          { providerKey: 'TEST_KEY', displayName: uniqueName, credential: plainCredential },
          actorId,
          'admin'
        );
        connId = conn.id;

        // Read the most recent audit_log_entries row for this resource.
        const auditRows = await db.execute<{
          content_hash: string;
          payload_hash: string;
          action: string;
          resource_id: string;
        }>(sql`
              SELECT action, resource_id, content_hash, payload_hash
              FROM audit_log_entries
              WHERE resource_type = 'data_source_connection'
                AND resource_id = ${connId}
              ORDER BY sequence_number DESC
              LIMIT 1
            `);
        const auditRow = (auditRows.rows ?? auditRows)[0];
        expect(auditRow).toBeDefined();
        expect(auditRow!.action).toBe('data-source-conn-upsert');

        // LOAD-BEARING: plaintext credential must NOT appear in any audit field.
        const auditStr = JSON.stringify(auditRow);
        expect(auditStr).not.toContain(plainCredential);
        // The connection record itself must not return the credential.
        expect(conn.hasCredential).toBe(true);
        const connStr = JSON.stringify(conn);
        expect(connStr).not.toContain(plainCredential);
        expect(connStr).not.toContain('encryptedCredentials');
      } finally {
        // WORM-SAFE: delete the connection (safe — data_source_connections is mutable).
        // Do NOT delete actorId: createConnection committed an audit row with
        // actor_user_id = actorId. Deleting the user would trigger ON DELETE SET NULL
        // on audit_log_entries.actor_user_id which the WORM trigger blocks (P0001).
        if (connId) await deleteTestConnection(connId);
      }
    });

    // ── SEC-2: Credential absent from forced-error path ───────────────────────

    it('SEC-2: credential is absent from the error when a DB constraint fires (unique displayName)', {
      timeout: 10000,
    }, async () => {
      if (!dbReachable) return;

      const actorId = await createTestUser(`admin-sec2-${Date.now()}@test.com`, 'admin');

      const { DataSourceAdminService } = await import(
        '../src/modules/admin/data-source-admin.service'
      );
      const { AuditService } = await import('../src/modules/audit/audit.service');
      const { AuditRepository } = await import('../src/modules/audit/audit.repository');
      const { AuditKeyring } = await import('../src/modules/audit/audit.keyring');

      const keyring = new AuditKeyring(process.env);
      const auditRepo = new AuditRepository(db);
      const auditService = new AuditService(keyring, auditRepo);
      const service = new DataSourceAdminService(db, auditService);

      const uniqueName = `SEC2-test-${Date.now()}`;
      const plainCredential = `forced-error-secret-${Date.now()}`;
      let firstConnId: string | undefined;

      try {
        // Create the first connection successfully.
        const first = await service.createConnection(
          { providerKey: 'TEST_KEY', displayName: uniqueName, credential: plainCredential },
          actorId,
          'admin'
        );
        firstConnId = first.id;

        // Attempt to create a SECOND connection with the SAME displayName → 23505 unique violation.
        const err = await service
          .createConnection(
            { providerKey: 'TEST_KEY2', displayName: uniqueName, credential: plainCredential },
            actorId,
            'admin'
          )
          .catch((e: unknown) => e);

        expect(err).toBeDefined();
        // LOAD-BEARING: the error message must not contain the plaintext credential.
        const errStr = String(err instanceof Error ? err.message : err);
        const errFull =
          err instanceof Error ? JSON.stringify(err, Object.getOwnPropertyNames(err)) : String(err);
        expect(errStr).not.toContain(plainCredential);
        expect(errFull).not.toContain(plainCredential);
      } finally {
        // WORM-SAFE: delete connection only (mutable table). Retain actorId.
        if (firstConnId) await deleteTestConnection(firstConnId);
      }
    });

    // ── SEC-3: Round-trip encrypt/decrypt with the test key ───────────────────

    it('SEC-3: round-trip encrypt → decrypt with the test CREDENTIALS_ENC_KEY', async () => {
      if (!dbReachable) return;

      const { encryptCredential, decryptCredential } = await import(
        '../src/modules/admin/credential-crypto'
      );
      const plaintext = 'round-trip-test-secret';
      const stored = encryptCredential(plaintext);
      const recovered = decryptCredential(stored);
      expect(recovered).toBe(plaintext);
    });

    // ── SEC-4: GET never returns credential ───────────────────────────────────

    it('SEC-4: listConnections (GET) never returns the credential even when one is stored', {
      timeout: 10000,
    }, async () => {
      if (!dbReachable) return;

      const actorId = await createTestUser(`admin-sec4-${Date.now()}@test.com`, 'admin');

      const { DataSourceAdminService } = await import(
        '../src/modules/admin/data-source-admin.service'
      );
      const { AuditService } = await import('../src/modules/audit/audit.service');
      const { AuditRepository } = await import('../src/modules/audit/audit.repository');
      const { AuditKeyring } = await import('../src/modules/audit/audit.keyring');

      const keyring = new AuditKeyring(process.env);
      const auditRepo = new AuditRepository(db);
      const auditService = new AuditService(keyring, auditRepo);
      const service = new DataSourceAdminService(db, auditService);

      const uniqueName = `SEC4-test-${Date.now()}`;
      const plainCredential = `list-test-secret-${Date.now()}`;
      let connId: string | undefined;

      try {
        const conn = await service.createConnection(
          { providerKey: 'TEST_KEY', displayName: uniqueName, credential: plainCredential },
          actorId,
          'admin'
        );
        connId = conn.id;

        // List connections and find ours.
        const list = await service.listConnections();
        const record = list.find((c) => c.id === connId);
        expect(record).toBeDefined();
        expect(record!.hasCredential).toBe(true);

        // LOAD-BEARING: plaintext must not appear in the list response.
        const listStr = JSON.stringify(list);
        expect(listStr).not.toContain(plainCredential);
        expect(listStr).not.toContain('encryptedCredentials');
      } finally {
        // WORM-SAFE: delete connection only. Retain actorId.
        if (connId) await deleteTestConnection(connId);
      }
    });
  }
);
